## Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

####################################
# Debug and Release Configurations #
####################################
project 'FourSquare-ios',
'Debug(Development)' => :debug,
'Release(Development)' => :release

target 'FourSquare-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FourSquare-ios

 
  #########
  # Media #
  #########
  pod 'Kingfisher'    # Image
  
  ##############
  # Networking #
  ##############
  pod 'Moya'
  pod 'PromiseKit'

end
